#!/bin/bash

set -eu

COMMAND_TO_RUN="$1"

NIX_PROFILE_SCRIPT="$HOME/.nix-profile/etc/profile.d/nix.sh"

function install_nix() {
    if  [ ! -e "$NIX_PROFILE_SCRIPT" ]; then
        echo "Installing the nix pacakge manager: http://nixos.org/nix/"
        curl https://nixos.org/nix/install | sh
    fi
}

install_nix

echo "Loading nix into shell"
. "$NIX_PROFILE_SCRIPT"

nix-shell --run "npm install && $COMMAND_TO_RUN"